name: variables and secrets

env:
  WF_VAR: "Workflow level variable"

on:
  push:
  
jobs:
  test_expressions:
    name: job to test expressions
    runs-on: ubuntu-latest
    env:
      aBoolean: ${{ false }}
      anNull: ${{ null }}
      aNumber: ${{ 42 }}
      aString: this is a string
  steps:
    - name: test null
      if: (env.aNull == null)
      run: echo this variable is null
    - name: test boolean
      if: ${{ fromJSON(env.aBoolean) }}
      run: echo this job wont run as our variable is false
    - name: contains function
      if: ${{ contains(env.aString, 'this') }}
      run: |
        echo "our sting var contains the word this"
        echos "but here is a typo that will make this step fail"
    - name: test status check and format function
      if: ${{ failure() }}
      env:
        FORMAT_VAR: ${{ format('GitHub {0} {1} {2}', 'actions', 'is', 'awsome!') }}
        run: |
          echo "this step runs a special script to clean up after the failed step."
          echo ${{ env.FORMAT_VAR }}
    - name: function and always status check
      if: ${{ startsWith(env.aSting, 'this') && always() )}
      run: sleep 60
    - name: test cancel status check
      if: ${{ cancelled() }}
      run: echo "this job runs if a workflow is cancelled, it can also be used for clean-up scripts"

      
  test_varibales:
    if: (github.event_name == 'pull_request')
      env:
        JOB_VAR: "Job level variable" 
      name: job to test variables
      runs-on: ubuntu-latest
      steps:
        - name: test variables
          id: stepVar
          env:
            STEP_VAR: "Step level variable"
          run: |
            echo ${{ github.actor }}
            echo $GITHUB_JOB
            echo $WF_VAR
            echo $JOB_VAR
            echo $STEP_VAR
            echo ${{ vars.CONF_VAR }}
            echo ${{ secrets.A_SECRET }}
